name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Replace secrets in Googles App Engine Deployment File
        uses: 73h/gae-app-yaml-replace-env-variables@v0.3
        env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY_ID }}
        with:
          app_yaml_path: "app.yaml"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_DEPLOY_CREDENTIALS }}

      - name: Authenticate with Google Cloud
        env:
          GOOGLE_DEPLOY_CREDENTIALS: ${{ secrets.GOOGLE_DEPLOY_CREDENTIALS }}
        run: |
          echo "$GOOGLE_DEPLOY_CREDENTIALS" > keyfile.json
          gcloud auth activate-service-account --key-file=keyfile.json

      - name: Deploy to App Engine
        run: gcloud app deploy --quiet